drop table if exists tmp_teams_ranking;
create temp table tmp_teams_ranking (
    season varchar(20),
    home_match int,
    away_match int,
    competition varchar(100),
    home_score int,
    away_score int,
    team varchar(20),
    att int,
    home_y_cards int,
    away_y_card int,
    home_yr_cards int,
    away_yr_cards int,
    home_r_cards int,
    away_r_cards int,
    home_fouls int,
    away_fouls int,
    home_shots int,
    away_shots int,
    home_shots_ot int,
    away_shots_ot int,
    home_goal_for int,
    away_goal_for int,
    home_goal_against int,
    away_goal_against int,
    home_clean_sheet int,
    away_clean_sheet int,
    home_xg_for numeric,
    away_xg_for numeric,
    home_xg_against numeric,
    away_xg_against numeric,
    home_points int,
    away_points int,
    home_x_points int,
    away_x_points int,
    home_win int,
    away_win int,
    home_draw int,
    away_draw int,
    home_lose int,
    away_lose int
);

drop table if exists tmp_justice_ranking;
create temp table tmp_justice_ranking (
    match varchar(20),
    "Club" varchar(100),
    played_home boolean,
    xg numeric,
    shots bigint
);

drop table if exists tmp_players_ranking;
create temp table tmp_players_ranking (
    season varchar(20),
    home_match int,
    away_match int,
    player varchar(20),
    competition varchar(100),
    team varchar(20),
    home_gk int,
    away_gk int,
    home_goals int,
    away_goals int,
    home_pens_made int,
    away_pens_made int,
    home_assists int,
    away_assists int,
    home_xg numeric,
    away_xg numeric,
    home_clean_sheet int,
    away_clean_sheet int,
    home_cards_yellow int,
    away_cards_yellow int,
    home_cards_red int,
    away_cards_red int,
    home_cards_yellow_red int,
    away_cards_yellow_red int,
    home_win int,
    away_win int,
    home_draw int,
    away_draw int,
    home_lose int,
    away_lose int,
    home_captain int,
    away_captain int,
    home_minutes int,
    away_minutes int,
    home_started int,
    away_started int,
    home_sub_in int,
    away_sub_in int,
    home_sub_out int,
    away_sub_out int
);