name: Building SoccerScrapingAnalytics library

on:
  push:
    branches: 
      - "main"
      - "feature/*"
  pull_request:
    branches: 
      - "main"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: make lint
      
    - name: Run tests with pytest
      run: make test