name: Updating SoccerScrapingAnalytics library

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update version in setup.py
      run: |
        # Récupérer la version courante depuis le fichier setup.py
        current_version=$(grep "version=" setup.py | sed -E "s/.*version='([^']+)'.*/\1/")
        
        # Diviser la version en major, minor, patch
        IFS='.' read -r major minor patch <<< "$current_version"
        
        # Si on est sur la branche 'main', incrémenter la version PATCH
        if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          tag_version="v$new_version"
        else
          # Sinon, ajouter '-snapshot' à la version
          new_version="$current_version-snapshot"
          tag_version="v$new_version"
        fi

        # Afficher la nouvelle version pour vérification
        echo "Current version: $current_version"
        echo "New version: $new_version"
        echo "Tag version: $tag_version"
        
        # Met à jour la version dans le fichier setup.py
        sed -i "s/version='[^']*'/version='$new_version'/" setup.py

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Commit et push du changement de version
        git add setup.py
        git commit -m "Update version to $new_version"
        git tag "$tag_version"
        
        # Push les modifications et le tag
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:$GITHUB_REF
        git push --tags
